### ISSUE TITLE
Habit

### ISSUE THREAD

**Issue by Productive2** [techlore-official/plexus#11]
The CSV file contains an entry with the name `Habit`. Searching on play store it is not obvious which app it is referring to (there are a lot of applications beginning with Habit, but none with the exact match as far as I scrolled down). 

Perhaps the closest is `Habit - habit tracker and goals in 21 days`. Perhaps the app was renamed, or the person who reported it used the app name in the launcher, not the play store name (the in-launcher name is `Habit`). The one I assumed to be habit is by Roman K. with the java package name `com.habit.application`. The java package name can be found by looking at the play store link https:// play.google.com /store/apps/details?id=**com.habit.application**&hl=en. Since the online play store uses package names to load data about apps, I assume that they are unique (perhaps application names are unique as well, to be honest I don't know, but application names can be changed).

Just to clarify, I am not trying to convince anyone to put package names in the csv right now, since I think it raises the entry bar to both understanding and contributing to plexus. But I'd like to point out that eventually if there was ever a website frontend, if package names were included in the csv, a script could easily load icons, download counts and other data from play store, and perhaps improve user experience. And solve the renaming/incomplete/ambiguous name problem some generic not so well known applications might have.

I tested version 1.1.2 from the aurora store. On android 9, no micro G, disabled netguard. Can confirm everything works in the app, except the rate on playstore button, so I confirm the score of 4. I also checked if notifications work, and they do.

**Comment by techlore-official** [comment]
The app is “Loop Habit Tracker”

Good catch, and I’ll update the CSV to fix this.
