### ISSUE TITLE
Paypal without gservices

### ISSUE THREAD

**Issue by 51ckb01** [techlore-official/plexus#122]
I think there is an error in the paypal score
[Paypal](https://plexus.techlore.tech/applications/pay-pal)
Installed app without google services (with aurora store) has no push notifications
Tested with LineageOS 17.1

**Comment by techlore-official** [comment]
https://github.com/techlore-official/plexus/commit/33d1baee8f16b194da0ab379290af73fd7d4def3

Just updated the listing.
