### ISSUE TITLE
What about apps on both F-Droid and Google Play?

### ISSUE THREAD

**Issue by TheLastProject** [techlore-official/plexus#123]
The README says this:

>NOTE: Plexus is only for applications directly or indirectly from the Google Play Store. Please do not submit applications from F-Droid as they are all expected to work.

What about apps on F-Droid and Google Play? For example, I release all my apps on both. Should I include my apps or not? https://play.google.com/store/apps/developer?id=Sylvia+van+Os

**Comment by techlore-official** [comment]
Nope these should be excluded for now to avoid confusion. I actually need to cleanup the database and remove some of those that slipped.

Once things are managed in a cleaner way then we can find a solution for multiple submissions and include source of the application and other data (OS, App version number, etc.) 

This is all being worked on.
