### ISSUE TITLE
Better explanations for new users

### ISSUE THREAD

**Issue by Hultan** [techlore-official/plexus#29]
I just, a week or so ago, installed **GrapheneOS** on my Pixel 3a, so I am very new to this. I read through the **Readme.md** and there were a lot of things I don't fully understand. I would like a better explanation of certain words and sentences, etc in the **readme.md**, so that I as a beginner can start reporting some apps to this project.

Generally, you talk about **MicroG**, but there is no real explanation for what it is? I download apps mostly from **F-droid**, but some are from **Aurora Store**. Is **MicroG** a competing store? Or is **MicroG** a service that **Aurora** is using? Or is it something else...I think a better explanation of **MicroG** is important here, since it is a term that is used all over the **readme.md**. The wiki (https://en.wikipedia.org/wiki/MicroG) didn't help me much either, since it does not mention GrapheneOS at all.

A couple of more  things that I think could benefit from a better explanation:

From the section **explanation**:
  _"**Plexus** supports ROMs with simply no Google Play Services, as well as ROMs with **MicroG**, an open source variation of Google Play Services."_

I don't know where, for example, **GrapheneOS** fits in here. Maybe give a few examples of each option here.

From the section **Testing standards**:
  _"Test only Google Play Store applications (Regardless of where they came from)"_

What does the last part mean? Does it mean **Aurora Store** for example? 

  _"No Google Play Services"_

What does this mean? Is there some setting I need to disable before testing apps? You say above that **MicroG** is an open source variation of Google Play Services, so, no **MicroG**? Or are you saying that **MicroG** is ok, because it is an open source variant of Google Play Services? I guess I am confused, because, again, I don't really know what **MicroG** is.

These are just some questions that I had after reading through the **readme.md**. For the time being I will hold off on contributing with a few apps, in fear of just reporting things wrong, and messing things up...

**Comment by Hultan** [comment]
Feel free to ignore this issue, I am on CalyxOS now, and therefor I know a tiny little bit more about MicroG. I guess what confused me was that GrapheneOS does not have MicroG, so I had never heard of it, but when I installed CalyxOS it asked me if I wanted to use MicroG. I still think the readme.md could be clearer about some things though.

**Comment by PrestoSole** [comment]
Hi Hultan, I know you no longer care about your issue but I already Pulled a request that better explains Plexus and microG with example ROMs for the newcomers.

**Comment by PrestoSole** [comment]
@Hultan, feel free to close this issue; my pull request got merged
