### ISSUE TITLE
Posibillity to ask for app tests?

### ISSUE THREAD

**Issue by innir** [techlore-official/plexus#38]
Hi,

thanks for the list!

I was wondering if it's a good idea to have a possibility to ask for app test somewhere - I'm planning to switch to a de-Googled  device but I need some apps and it's obviously hard for me to test but only an install away for others ;-)
Specifically they are:

https://play.google.com/store/apps/details?id=de.ard.audiothek
https://play.google.com/store/apps/details?id=de.deutschlandfunk.dlfaudiothek
https://play.google.com/store/apps/details?id=de.eos.uptrade.android.fahrinfo.hamburg
https://play.google.com/store/apps/details?id=de.deutschlandradio.dlf24

... just close the issue if you think it's not the right place / way to ask for app test ...

Best

**Comment by techlore-official** [comment]
On the readme under Future Plans, it’s on our radar to include a method of requesting apps to test in the future. This isn’t currently supported but will be down the road.

**Comment by mak448a** [comment]
Sorry to bother, but is this still planned? I didn't see it in the roadmap on the README.
